version: '3.9'

services:
  backend:
    build:
      context: ./backend
    image: rag-backend
    container_name: rag-backend-container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    restart: always

  frontend:
    build:
      context: ./frontend/rag-analysis
    image: rag-frontend
    container_name: rag-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
